# Generated by Django 5.0.6 on 2024-06-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_produ', models.AutoField(db_column='idProdu', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='media')),
                ('stock', models.IntegerField(null=True)),
                ('id_tipo', models.ForeignKey(db_column='idTipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.tipoproducto')),
            ],
        ),
    ]
